INSERT INTO companies (
    ruc,
    razon_social,
    nombre_comercial,
    direccion,
    ubigeo,
    departamento,
    provincia,
    distrito,
    urbanizacion,
    cod_local,
    sol_user,
    sol_pass,
    certificado_sunat,
    ambiente,
    created,
    modified
) VALUES (
    '20609186039',
    'CAYCHO CABRERA & ASOCIADOS S.A.C.',
    'CONSULTORIO GINECOLÓGICO JYZA',
    'JR. 2 DE MAYO NRO. 1600',
    NULL,
    'HUANUCO',
    'HUANUCO',
    'HUANUCO',
    NULL,
    '0000',
    'USERSECU',
    'QPdan98user',
    'certificados/certificadojyza.pem',
    'produccion',
    NOW(),
    NOW()
);